// Generated by Comline
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Scalars {
    pub flag: bool,
    pub small: u8,
    pub medium: u32,
    pub large: u64,
    pub huge: u128,
    pub signed_small: i8,
    pub signed_large: i64,
    pub name: String,
}

