// Generated by Comline

export interface Scalars {
    flag: boolean;
    small: number;
    medium: number;
    large: number;
    huge: u128;
    signed_small: number;
    signed_large: number;
    name: string;
}

