// Generated by Comline
use serde::{Deserialize, Serialize};
use comline_runtime::client::Client;
use comline_runtime::contract::{
    Call, CallError, Dispatch, Envelope, Handshake, Kind, Reply, RuntimeError,
    WireFormat, FRAMING_DATAGRAM,
};
use comline_runtime::serve::Server;
use comline_runtime::transport::Transport;

/// Canonical digest of the frozen IR this file was generated from — the
/// two ends of a connection [`Handshake`] must agree on it.
pub const IR_HASH: u64 = 0xbdbe5c6fd7420bd0;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NotFound {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServiceLookupParams {
    pub id: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServiceNotifyParams {
    pub code: u16,
}

#[derive(Debug, Clone, PartialEq)]
pub enum ServiceLookupError {
    NotFound(NotFound),
}

#[derive(Debug, Clone, PartialEq)]
pub enum ServiceCountError {
}

#[derive(Debug, Clone, PartialEq)]
pub enum ServiceError {
    NotFound(NotFound),
}

impl From<ServiceLookupError> for ServiceError {
    fn from(e: ServiceLookupError) -> Self {
        match e {
            ServiceLookupError::NotFound(x) => ServiceError::NotFound(x),
        }
    }
}

pub trait Service {
    fn lookup(&self, id: i32) -> Result<Record, ServiceLookupError>;
    fn count(&self) -> Result<u64, ServiceCountError>;
    fn notify(&self, code: u16);
}

pub const SERVICE_CALLS: &[&str] = &["lookup", "count", "notify"];

pub struct ServiceDispatcher<S>(pub S);

impl<S: Service> Dispatch for ServiceDispatcher<S> {
    fn calls(&self) -> &'static [&'static str] {
        SERVICE_CALLS
    }

    fn dispatch<W: WireFormat>(
        &self,
        call: Kind,
        params: &[u8],
        fmt: &W,
        reply: &mut Reply,
    ) -> Result<(), RuntimeError> {
        match call.resolve(SERVICE_CALLS).ok_or(RuntimeError::UnknownCall)? {
            0 => {
                let p: ServiceLookupParams = fmt.decode(params)?;
                match self.0.lookup(p.id) {
                    Ok(value) => {
                        let mut body = Vec::new();
                        fmt.encode(&value, &mut body)?;
                        reply.ok(&body);
                    }
                    Err(ServiceLookupError::NotFound(e)) => {
                        let mut body = Vec::new();
                        fmt.encode(&e, &mut body)?;
                        reply.err(0u16, &body);
                    }
                }
                Ok(())
            }
            1 => {
                let _: () = fmt.decode(params)?;
                match self.0.count() {
                    Ok(value) => {
                        let mut body = Vec::new();
                        fmt.encode(&value, &mut body)?;
                        reply.ok(&body);
                    }
                    Err(never) => match never {},
                }
                Ok(())
            }
            2 => {
                let p: ServiceNotifyParams = fmt.decode(params)?;
                self.0.notify(p.code);
                Ok(())
            }
            _ => Err(RuntimeError::UnknownCall),
        }
    }
}

impl<S: Service> ServiceDispatcher<S> {
    /// Serve this protocol over `transport`, running the connection
    /// handshake (`IR_HASH` + `format`'s name) against the peer first.
    pub fn serve<T: Transport, W: WireFormat>(self, transport: &mut T, format: W)
    -> Result<(), RuntimeError> {
        let hs = Handshake::new(IR_HASH, format.name(), FRAMING_DATAGRAM, 0);
        Server::new(self, format).serve_handshaked(transport, hs)
    }
}

pub struct ServiceClient<T, W>(pub Client<T, W>);

impl<T: Transport, W: WireFormat> ServiceClient<T, W> {
    pub fn new(client: Client<T, W>) -> Self {
        Self(client)
    }

    /// Bind + run the connection handshake against the provider.
    pub fn connect(transport: T, format: W) -> Result<Self, RuntimeError> {
        let hs = Handshake::new(IR_HASH, format.name(), FRAMING_DATAGRAM, 0);
        Ok(Self(Client::connect(transport, format, hs)?))
    }

    pub fn lookup(&mut self, id: i32) -> Result<Record, CallError<ServiceLookupError>> {
        let (reply, fmt) = self.0.call(Call::new(0, "lookup"), &ServiceLookupParams { id })?;
        match reply {
            Envelope::Ok(payload) => fmt.decode(payload).map_err(CallError::Runtime),
            Envelope::Err { id: 0u16, body } => {
                let e: NotFound = fmt.decode(body)?;
                Err(CallError::App(ServiceLookupError::NotFound(e)))
            }
            Envelope::Err { id, .. } => Err(CallError::Runtime(RuntimeError::Remote { id })),
        }
    }

    pub fn count(&mut self) -> Result<u64, CallError<ServiceCountError>> {
        let (reply, fmt) = self.0.call(Call::new(1, "count"), &())?;
        match reply {
            Envelope::Ok(payload) => fmt.decode(payload).map_err(CallError::Runtime),
            Envelope::Err { id, .. } => Err(CallError::Runtime(RuntimeError::Remote { id })),
        }
    }

    pub fn notify(&mut self, code: u16) -> Result<(), RuntimeError> {
        self.0.notify(Call::new(2, "notify"), &ServiceNotifyParams { code })
    }
}

