// Generated by Comline
use serde::{Deserialize, Serialize};
use comline_runtime::client::Client;
use comline_runtime::contract::{
    BufMut, CallError, Dispatch, Envelope, Kind, RuntimeError, WireFormat,
};
use comline_runtime::transport::Transport;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NotFound {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServiceLookupParams {
    pub id: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServiceNotifyParams {
    pub code: u16,
}

#[derive(Debug, Clone, PartialEq)]
pub enum ServiceLookupError {
    NotFound(NotFound),
}

#[derive(Debug, Clone, PartialEq)]
pub enum ServiceCountError {
}

#[derive(Debug, Clone, PartialEq)]
pub enum ServiceError {
    NotFound(NotFound),
}

impl From<ServiceLookupError> for ServiceError {
    fn from(e: ServiceLookupError) -> Self {
        match e {
            ServiceLookupError::NotFound(x) => ServiceError::NotFound(x),
        }
    }
}

pub trait Service {
    fn lookup(&self, id: i32) -> Result<Record, ServiceLookupError>;
    fn count(&self) -> Result<u64, ServiceCountError>;
    fn notify(&self, code: u16);
}

pub const SERVICE_CALLS: &[&str] = &["lookup", "count", "notify"];

pub struct ServiceDispatcher<S>(pub S);

impl<S: Service> Dispatch for ServiceDispatcher<S> {
    fn dispatch<W: WireFormat>(
        &self,
        call: Kind,
        params: &[u8],
        fmt: &W,
        out: &mut dyn BufMut,
    ) -> Result<(), RuntimeError> {
        match call.resolve(SERVICE_CALLS).ok_or(RuntimeError::UnknownCall)? {
            0 => {
                let p: ServiceLookupParams = fmt.decode(params)?;
                match self.0.lookup(p.id) {
                    Ok(reply) => {
                        let mut body = Vec::new();
                        fmt.encode(&reply, &mut body)?;
                        Envelope::encode_ok(&body, out);
                    }
                    Err(ServiceLookupError::NotFound(e)) => {
                        let mut body = Vec::new();
                        fmt.encode(&e, &mut body)?;
                        Envelope::encode_err(0u16, &body, out);
                    }
                }
                Ok(())
            }
            1 => {
                let _: () = fmt.decode(params)?;
                match self.0.count() {
                    Ok(reply) => {
                        let mut body = Vec::new();
                        fmt.encode(&reply, &mut body)?;
                        Envelope::encode_ok(&body, out);
                    }
                    Err(never) => match never {},
                }
                Ok(())
            }
            2 => {
                let p: ServiceNotifyParams = fmt.decode(params)?;
                self.0.notify(p.code);
                Ok(())
            }
            _ => Err(RuntimeError::UnknownCall),
        }
    }
}

pub struct ServiceClient<T, W>(pub Client<T, W>);

impl<T: Transport, W: WireFormat> ServiceClient<T, W> {
    pub fn new(client: Client<T, W>) -> Self {
        Self(client)
    }

    pub fn lookup(&mut self, id: i32) -> Result<Record, CallError<ServiceLookupError>> {
        let (reply, fmt) = self.0.call(0u16, &ServiceLookupParams { id })?;
        match reply {
            Envelope::Ok(payload) => fmt.decode(payload).map_err(CallError::Runtime),
            Envelope::Err { id: 0u16, body } => {
                let e: NotFound = fmt.decode(body)?;
                Err(CallError::App(ServiceLookupError::NotFound(e)))
            }
            Envelope::Err { id, .. } => Err(CallError::Runtime(RuntimeError::Remote { id })),
        }
    }

    pub fn count(&mut self) -> Result<u64, CallError<ServiceCountError>> {
        let (reply, fmt) = self.0.call(1u16, &())?;
        match reply {
            Envelope::Ok(payload) => fmt.decode(payload).map_err(CallError::Runtime),
            Envelope::Err { id, .. } => Err(CallError::Runtime(RuntimeError::Remote { id })),
        }
    }

    pub fn notify(&mut self, code: u16) -> Result<(), RuntimeError> {
        self.0.notify(2u16, &ServiceNotifyParams { code })
    }
}

