// Generated by Comline

// Canonical digest of the frozen IR this file was generated from — the
// two ends of a connection must agree on it.
export const IR_HASH = 0xbdbe5c6fd7420bd0n;

export interface NotFound {
}

export interface ServiceLookupParams {
    id: number;
}

export interface ServiceNotifyParams {
    code: number;
}

export type ServiceLookupError =
    | { code: 0; name: "NotFound"; data: NotFound };

export type ServiceError =
    | { code: 0; name: "NotFound"; data: NotFound };

export interface Service {
    /** @throws {ServiceLookupError} */
    lookup(params: ServiceLookupParams): Promise<Record>;
    count(): Promise<number>;
    notify(params: ServiceNotifyParams): Promise<void>;
}

