// Generated by Comline
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Bag {
    pub required: String,
    pub maybe: u32,
    pub many: Vec<String>,
    pub maybe_many: Vec<u32>,
}

