// Generated by Comline
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Bag {
    pub required: String,
    pub maybe: Option<u32>,
    pub many: Vec<String>,
    pub maybe_many: Option<Vec<u32>>,
}

