// Generated by Comline
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Inner {
    pub value: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Outer {
    pub one: Inner,
    pub some: Option<Inner>,
    pub list: Vec<Inner>,
}

