// Generated by Comline
use serde::{Serialize, Deserialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Inner {
    pub value: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Outer {
    pub one: Inner,
    pub some: Inner,
    pub list: Vec<Inner>,
}

