//! Rust generation.
//!
//! - `code` — one `<namespace>.rs` per schema: serde data types, plain traits,
//!   C-like enums (ported from `comline-core`'s `codelib_gen::rust` in de-rot G1).
//! - `lib` — a buildable crate: `Cargo.toml` + `src/lib.rs` (the `pub mod` tree)
//!   + `src/<namespace>.rs`. See design/generation.md.

use std::path::PathBuf;

use comline_core::schema::ir::frozen::unit::FrozenUnit;
use comline_core::schema::ir::compiler::interpreted::kind_search::KindValue;

use eyre::{bail, Result};

use comline_codegen::{GenRequest, GeneratedFile, Mode, PackageMeta};


pub fn generate_rust(req: &GenRequest) -> Result<Vec<GeneratedFile>> {
    match req.mode {
        Mode::Code => Ok(req
            .schemas
            .iter()
            .map(|(namespace, units)| GeneratedFile {
                path: PathBuf::from(format!("{namespace}.rs")),
                contents: schema_source(units),
            })
            .collect()),

        Mode::Lib => {
            require_flat_namespaces(req.schemas)?;

            let mut files = vec![
                GeneratedFile {
                    path: PathBuf::from("Cargo.toml"),
                    contents: cargo_toml(&req.package),
                },
                GeneratedFile {
                    path: PathBuf::from("src/lib.rs"),
                    contents: lib_rs(req.schemas),
                },
            ];
            for (namespace, units) in req.schemas {
                files.push(GeneratedFile {
                    path: PathBuf::from(format!("src/{namespace}.rs")),
                    contents: schema_source(units),
                });
            }
            Ok(files)
        }
    }
}

/// `lib` mode emits a flat `pub mod <namespace>;` list; a `/`-joined namespace
/// would need an intermediate module tree. Not built yet.
fn require_flat_namespaces(schemas: &[(String, Vec<FrozenUnit>)]) -> Result<()> {
    for (namespace, _) in schemas {
        if namespace.contains('/') {
            bail!(
                "rust lib mode does not support nested namespaces yet \
                 (namespace `{namespace}`)"
            );
        }
    }
    Ok(())
}

fn cargo_toml(pkg: &PackageMeta) -> String {
    format!(
        "# Generated by Comline\n\
         [package]\n\
         name = \"{}\"\n\
         version = \"{}\"\n\
         edition = \"2021\"\n\
         # A schema namespace named `main` would otherwise be picked up as a\n\
         # binary target (`src/main.rs`) with no `fn main`.\n\
         autobins = false\n\
         \n\
         [dependencies]\n\
         serde = {{ version = \"1\", features = [\"derive\"] }}\n",
        pkg.name, pkg.version
    )
}

fn lib_rs(schemas: &[(String, Vec<FrozenUnit>)]) -> String {
    let mut s = String::from("// Generated by Comline\n\n");
    for (namespace, _) in schemas {
        s.push_str(&format!("pub mod {namespace};\n"));
    }
    s
}

fn schema_source(units: &[FrozenUnit]) -> String {
    let mut output = String::new();
    output.push_str("// Generated by Comline\n");
    output.push_str("use serde::{Serialize, Deserialize};\n\n");

    for unit in units {
        match unit {
            FrozenUnit::Struct { name, fields, .. } => {
                output.push_str(&generate_struct(name, fields));
            }
            FrozenUnit::Enum { name, variants, .. } => {
                output.push_str(&generate_enum(name, variants));
            }
            FrozenUnit::Protocol { name, functions, .. } => {
                output.push_str(&generate_protocol(name, functions));
            }
            _ => {}
        }
    }

    output
}

fn generate_struct(name: &str, fields: &Vec<FrozenUnit>) -> String {
    let mut s = format!("#[derive(Debug, Clone, Serialize, Deserialize)]\npub struct {} {{\n", name);

    for field in fields {
        if let FrozenUnit::Field { name, kind_value, .. } = field {
            let type_name = map_kind_to_rust_type(kind_value);
            s.push_str(&format!("    pub {}: {},\n", name, type_name));
        }
    }

    s.push_str("}\n\n");
    s
}

fn generate_protocol(name: &str, functions: &Vec<FrozenUnit>) -> String {
    let mut s = format!("pub trait {} {{\n", name);

    for func in functions {
        if let FrozenUnit::Function { name, arguments, _return, .. } = func {
            let args_str = arguments.iter().map(|arg| {
                 format!("{}: {}", arg.name, map_kind_to_rust_type(&arg.kind))
            }).collect::<Vec<_>>().join(", ");

            let ret_str = if let Some(ret) = _return {
                format!(" -> {}", map_kind_to_rust_type(ret))
            } else {
                "".to_string()
            };

            s.push_str(&format!("    fn {}({}){};\n", name, args_str, ret_str));
        }
    }

    s.push_str("}\n\n");
    s
}

fn generate_enum(name: &str, variants: &Vec<FrozenUnit>) -> String {
    let mut s = format!("#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]\npub enum {} {{\n", name);

    for variant in variants {
        if let FrozenUnit::EnumVariant(kv, _) = variant {
            let variant_name = match kv {
                KindValue::EnumVariant(n, _) => n.clone(),
                KindValue::Namespaced(n, _) => n.clone(), // Fallback
                _ => "Unknown".to_string(),
            };
             s.push_str(&format!("    {},\n", variant_name));
        }
    }

    s.push_str("}\n\n");
    s
}

fn map_kind_to_rust_type(kind: &KindValue) -> String {
    match kind {
        KindValue::Primitive(p) => {
             map_str_type(p.name())
        }
        KindValue::Namespaced(name, _) => {
             map_str_type(name)
        }
        KindValue::EnumVariant(name, _) => name.clone(),
        _ => "/* unknown_kind */".to_string()
    }
}

fn map_str_type(s: &str) -> String {
    if s.ends_with("[]") {
        let inner = &s[..s.len()-2];
        return format!("Vec<{}>", map_str_type(inner));
    }
    match s {
        "string" | "str" => "String".to_string(),
        "bool" => "bool".to_string(),
        "float" => "f64".to_string(),
        "int" => "i32".to_string(), // default to i32 for generic int
        "u8" => "u8".to_string(),
        "u16" => "u16".to_string(),
        "u32" => "u32".to_string(),
        "u64" => "u64".to_string(),
        // IDL spells signed integers with an `s` prefix (s8/s16/s32/s64);
        // Rust's own primitives are always `i`-prefixed, so this is a real
        // translation, not a passthrough.
        "s8" => "i8".to_string(),
        "s16" => "i16".to_string(),
        "s32" => "i32".to_string(),
        "s64" => "i64".to_string(),
        other => other.to_string(),
    }
}
