//! TypeScript `code`-mode generation: frozen IR -> `.ts` source.
//!
//! - `struct`   -> `export interface`
//! - `enum`     -> `export enum` with string values (JSON interop)
//! - `protocol` -> `export interface` with a method per function
//!
//! `lib` mode (an npm package) is not built yet. See design/generation.md.

use std::path::PathBuf;

use comline_core::schema::ir::frozen::unit::FrozenUnit;
use comline_core::schema::ir::compiler::interpreted::kind_search::KindValue;

use eyre::{bail, Result};

use comline_codegen::{GenRequest, GeneratedFile, Mode};


pub fn generate_typescript(req: &GenRequest) -> Result<Vec<GeneratedFile>> {
    if req.mode == Mode::Lib {
        bail!("typescript lib mode is not implemented yet (de-rot G2)");
    }

    Ok(req
        .schemas
        .iter()
        .map(|(namespace, units)| GeneratedFile {
            path: PathBuf::from(format!("{namespace}.ts")),
            contents: schema_source(units),
        })
        .collect())
}

fn schema_source(units: &[FrozenUnit]) -> String {
    let mut output = String::new();
    output.push_str("// Generated by Comline\n\n");

    for unit in units {
        match unit {
            FrozenUnit::Struct { name, fields, .. } => {
                output.push_str(&generate_interface(name, fields));
            }
            FrozenUnit::Enum { name, variants, .. } => {
                output.push_str(&generate_enum(name, variants));
            }
            FrozenUnit::Protocol { name, functions, .. } => {
                output.push_str(&generate_protocol(name, functions));
            }
            _ => {}
        }
    }

    output
}

fn generate_interface(name: &str, fields: &Vec<FrozenUnit>) -> String {
    let mut s = format!("export interface {} {{\n", name);

    for field in fields {
        if let FrozenUnit::Field { name, kind_value, optional, .. } = field {
            let opt = if *optional { "?" } else { "" };
            s.push_str(&format!("    {}{}: {};\n", name, opt, map_kind_to_ts_type(kind_value)));
        }
    }

    s.push_str("}\n\n");
    s
}

fn generate_protocol(name: &str, functions: &Vec<FrozenUnit>) -> String {
    let mut s = format!("export interface {} {{\n", name);

    for func in functions {
        if let FrozenUnit::Function { name, arguments, _return, .. } = func {
            let args = arguments
                .iter()
                .map(|arg| format!("{}: {}", arg.name, map_kind_to_ts_type(&arg.kind)))
                .collect::<Vec<_>>()
                .join(", ");

            let ret = match _return {
                Some(r) => map_kind_to_ts_type(r),
                None => "void".to_string(),
            };

            s.push_str(&format!("    {}({}): {};\n", name, args, ret));
        }
    }

    s.push_str("}\n\n");
    s
}

fn generate_enum(name: &str, variants: &Vec<FrozenUnit>) -> String {
    let mut s = format!("export enum {} {{\n", name);

    for variant in variants {
        if let FrozenUnit::EnumVariant(kv, _) = variant {
            let variant_name = match kv {
                KindValue::EnumVariant(n, _) => n.clone(),
                KindValue::Namespaced(n, _) => n.clone(),
                _ => "Unknown".to_string(),
            };
            s.push_str(&format!("    {} = \"{}\",\n", variant_name, variant_name));
        }
    }

    s.push_str("}\n\n");
    s
}

fn map_kind_to_ts_type(kind: &KindValue) -> String {
    match kind {
        KindValue::Primitive(p) => map_str_type(p.name()),
        KindValue::Namespaced(name, _) => map_str_type(name),
        KindValue::EnumVariant(name, _) => name.clone(),
        _ => "unknown".to_string(),
    }
}

fn map_str_type(s: &str) -> String {
    if s.ends_with("[]") {
        let inner = &s[..s.len() - 2];
        return format!("{}[]", map_str_type(inner));
    }
    match s {
        "string" | "str" => "string".to_string(),
        "bool" => "boolean".to_string(),
        // TypeScript has one numeric type; every IDL integer / float width maps to it.
        "float" | "int" | "u8" | "u16" | "u32" | "u64" | "s8" | "s16" | "s32" | "s64" => {
            "number".to_string()
        }
        // A named type from the schema (another struct / enum) — pass through.
        other => other.to_string(),
    }
}
